# version: '3'
# services:
#   db:
#     image: mysql:latest
#     environment:
#       MYSQL_DATABASE: hobbinity_development
#       MYSQL_USER: 'root'
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#     ports:
#       - '3036:3036'
#     volumes:
#       - ./mysql-confd:/etc/mysql/conf.d
#       - mysql_data:/var/lib/mysql
    
#   web:
#     build:
#       context: .
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     tty: true
#     stdin_open: true
#     depends_on:
#       - db
#     ports:
#       - "3000:3000" 
#     volumes:
#       - .:/myproject
#       - bundle:/usr/local/bundle
# volumes:
#   mysql_data:
#   bundle:
